-- Migration 002: Seed harvested_tokens from curated MOCK data
-- Frequency is represented by repeated rows (used in weighted random sampling)
-- Subject
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young adult Asian woman, confident expression, glossy skin');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Female anime character, long dark hair, shy hesitant gesture');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Female anime character, long dark hair, shy hesitant gesture');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Female anime character, long dark hair, shy hesitant gesture');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Female anime character, long dark hair, shy hesitant gesture');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Female anime character, long dark hair, shy hesitant gesture');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Female anime character, long dark hair, shy hesitant gesture');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Female anime character, long dark hair, shy hesitant gesture');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Female anime character, long dark hair, shy hesitant gesture');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Korean woman, soft features, melancholy expression');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Korean woman, soft features, melancholy expression');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Korean woman, soft features, melancholy expression');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Korean woman, soft features, melancholy expression');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Korean woman, soft features, melancholy expression');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Korean woman, soft features, melancholy expression');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young woman, early 20s, platinum blonde hair, doe eyes');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young woman, early 20s, platinum blonde hair, doe eyes');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young woman, early 20s, platinum blonde hair, doe eyes');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young woman, early 20s, platinum blonde hair, doe eyes');
INSERT INTO harvested_tokens (token, value) VALUES ('Subject', 'Young woman, early 20s, platinum blonde hair, doe eyes');
-- Style
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Luxury glossy realism, hyper-detailed cinematic photography');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Hyperrealistic anime portrait, high contrast rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Hyperrealistic anime portrait, high contrast rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Hyperrealistic anime portrait, high contrast rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Hyperrealistic anime portrait, high contrast rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Hyperrealistic anime portrait, high contrast rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Hyperrealistic anime portrait, high contrast rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Hyperrealistic anime portrait, high contrast rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Hyperrealistic anime portrait, high contrast rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Hyperrealistic anime portrait, high contrast rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', '35mm analog film grain, Kodak Portra 400');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', '35mm analog film grain, Kodak Portra 400');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', '35mm analog film grain, Kodak Portra 400');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', '35mm analog film grain, Kodak Portra 400');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', '35mm analog film grain, Kodak Portra 400');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', '35mm analog film grain, Kodak Portra 400');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', '35mm analog film grain, Kodak Portra 400');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Early-2000s digital camera aesthetic, subtle grain');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Early-2000s digital camera aesthetic, subtle grain');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Early-2000s digital camera aesthetic, subtle grain');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Early-2000s digital camera aesthetic, subtle grain');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'Early-2000s digital camera aesthetic, subtle grain');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'DSLR fashion editorial, vivid cinematic color grade');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'DSLR fashion editorial, vivid cinematic color grade');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'DSLR fashion editorial, vivid cinematic color grade');
INSERT INTO harvested_tokens (token, value) VALUES ('Style', 'DSLR fashion editorial, vivid cinematic color grade');
-- Lighting
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Neon city lighting, glossy sporty highlights, luxury contrast');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Narrow beam spotlight, sharp dramatic falloff, deep darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Narrow beam spotlight, sharp dramatic falloff, deep darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Narrow beam spotlight, sharp dramatic falloff, deep darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Narrow beam spotlight, sharp dramatic falloff, deep darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Narrow beam spotlight, sharp dramatic falloff, deep darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Narrow beam spotlight, sharp dramatic falloff, deep darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Narrow beam spotlight, sharp dramatic falloff, deep darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Narrow beam spotlight, sharp dramatic falloff, deep darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Narrow beam spotlight, sharp dramatic falloff, deep darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Deep amber late golden hour, warm melancholy quality');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Deep amber late golden hour, warm melancholy quality');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Deep amber late golden hour, warm melancholy quality');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Deep amber late golden hour, warm melancholy quality');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Deep amber late golden hour, warm melancholy quality');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Deep amber late golden hour, warm melancholy quality');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Deep amber late golden hour, warm melancholy quality');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Harsh super-flash, bright blown-out highlights, retro fill');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Harsh super-flash, bright blown-out highlights, retro fill');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Harsh super-flash, bright blown-out highlights, retro fill');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Harsh super-flash, bright blown-out highlights, retro fill');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Harsh super-flash, bright blown-out highlights, retro fill');
INSERT INTO harvested_tokens (token, value) VALUES ('Lighting', 'Harsh super-flash, bright blown-out highlights, retro fill');
-- Scene
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Luxury rooftop tennis court at night, city skyline, neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Luxury rooftop tennis court at night, city skyline, neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Luxury rooftop tennis court at night, city skyline, neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Luxury rooftop tennis court at night, city skyline, neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Luxury rooftop tennis court at night, city skyline, neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Luxury rooftop tennis court at night, city skyline, neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Luxury rooftop tennis court at night, city skyline, neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Luxury rooftop tennis court at night, city skyline, neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Quiet classroom, end of day, golden light from large window');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Quiet classroom, end of day, golden light from large window');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Quiet classroom, end of day, golden light from large window');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Quiet classroom, end of day, golden light from large window');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Quiet classroom, end of day, golden light from large window');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Quiet classroom, end of day, golden light from large window');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Quiet classroom, end of day, golden light from large window');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Completely black background, no environment detail');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Completely black background, no environment detail');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Completely black background, no environment detail');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Completely black background, no environment detail');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Completely black background, no environment detail');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Completely black background, no environment detail');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Completely black background, no environment detail');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Completely black background, no environment detail');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Completely black background, no environment detail');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Nostalgic early-2000s bedroom, CD player, pop posters');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Nostalgic early-2000s bedroom, CD player, pop posters');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Nostalgic early-2000s bedroom, CD player, pop posters');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Nostalgic early-2000s bedroom, CD player, pop posters');
INSERT INTO harvested_tokens (token, value) VALUES ('Scene', 'Nostalgic early-2000s bedroom, CD player, pop posters');
-- Clothing
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Deep-red luxury tennis outfit, fitted sporty dress, premium fabric');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Deep-red luxury tennis outfit, fitted sporty dress, premium fabric');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Deep-red luxury tennis outfit, fitted sporty dress, premium fabric');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Deep-red luxury tennis outfit, fitted sporty dress, premium fabric');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Deep-red luxury tennis outfit, fitted sporty dress, premium fabric');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Deep-red luxury tennis outfit, fitted sporty dress, premium fabric');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Deep-red luxury tennis outfit, fitted sporty dress, premium fabric');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Sage green linen button-down, high-waisted rust wide-leg trousers');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Sage green linen button-down, high-waisted rust wide-leg trousers');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Sage green linen button-down, high-waisted rust wide-leg trousers');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Sage green linen button-down, high-waisted rust wide-leg trousers');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Sage green linen button-down, high-waisted rust wide-leg trousers');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Yellow BANANA crop tee, white tennis skort, black cap worn backwards');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Yellow BANANA crop tee, white tennis skort, black cap worn backwards');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Yellow BANANA crop tee, white tennis skort, black cap worn backwards');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Yellow BANANA crop tee, white tennis skort, black cap worn backwards');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Black long-sleeve knit sweater, body in darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Black long-sleeve knit sweater, body in darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Black long-sleeve knit sweater, body in darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Black long-sleeve knit sweater, body in darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Black long-sleeve knit sweater, body in darkness');
INSERT INTO harvested_tokens (token, value) VALUES ('Clothing', 'Black long-sleeve knit sweater, body in darkness');
-- Mood
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Bold, luxury, sporty nightlife energy, modern feminine confidence');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Bold, luxury, sporty nightlife energy, modern feminine confidence');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Bold, luxury, sporty nightlife energy, modern feminine confidence');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Bold, luxury, sporty nightlife energy, modern feminine confidence');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Bold, luxury, sporty nightlife energy, modern feminine confidence');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Bold, luxury, sporty nightlife energy, modern feminine confidence');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Bold, luxury, sporty nightlife energy, modern feminine confidence');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Bold, luxury, sporty nightlife energy, modern feminine confidence');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Bold, luxury, sporty nightlife energy, modern feminine confidence');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Bold, luxury, sporty nightlife energy, modern feminine confidence');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Dark, moody, dramatic, mysterious atmosphere');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Dark, moody, dramatic, mysterious atmosphere');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Dark, moody, dramatic, mysterious atmosphere');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Dark, moody, dramatic, mysterious atmosphere');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Dark, moody, dramatic, mysterious atmosphere');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Dark, moody, dramatic, mysterious atmosphere');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Dark, moody, dramatic, mysterious atmosphere');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Dark, moody, dramatic, mysterious atmosphere');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Quietly devastating, time passing without drama');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Quietly devastating, time passing without drama');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Quietly devastating, time passing without drama');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Quietly devastating, time passing without drama');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Quietly devastating, time passing without drama');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Quietly devastating, time passing without drama');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Nostalgic, playful, authentic 2000s energy');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Nostalgic, playful, authentic 2000s energy');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Nostalgic, playful, authentic 2000s energy');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Nostalgic, playful, authentic 2000s energy');
INSERT INTO harvested_tokens (token, value) VALUES ('Mood', 'Nostalgic, playful, authentic 2000s energy');
-- Composition
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Single vertical image, clean cinematic portrait framing');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Single vertical image, clean cinematic portrait framing');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Single vertical image, clean cinematic portrait framing');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Single vertical image, clean cinematic portrait framing');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Single vertical image, clean cinematic portrait framing');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Single vertical image, clean cinematic portrait framing');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Single vertical image, clean cinematic portrait framing');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Single vertical image, clean cinematic portrait framing');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Single vertical image, clean cinematic portrait framing');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Face centered in spotlight, body dissolves into black, tight frame');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Face centered in spotlight, body dissolves into black, tight frame');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Face centered in spotlight, body dissolves into black, tight frame');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Face centered in spotlight, body dissolves into black, tight frame');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Face centered in spotlight, body dissolves into black, tight frame');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Face centered in spotlight, body dissolves into black, tight frame');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Face centered in spotlight, body dissolves into black, tight frame');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Medium distance, mid-thigh up, shallow depth of field');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Medium distance, mid-thigh up, shallow depth of field');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Medium distance, mid-thigh up, shallow depth of field');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Medium distance, mid-thigh up, shallow depth of field');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Medium distance, mid-thigh up, shallow depth of field');
INSERT INTO harvested_tokens (token, value) VALUES ('Composition', 'Medium distance, mid-thigh up, shallow depth of field');
-- Technical
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Ultra realistic 4K, natural skin texture, realistic neon reflections');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'High contrast, sharp spotlight edges, hyperrealistic rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'High contrast, sharp spotlight edges, hyperrealistic rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'High contrast, sharp spotlight edges, hyperrealistic rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'High contrast, sharp spotlight edges, hyperrealistic rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'High contrast, sharp spotlight edges, hyperrealistic rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'High contrast, sharp spotlight edges, hyperrealistic rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'High contrast, sharp spotlight edges, hyperrealistic rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'High contrast, sharp spotlight edges, hyperrealistic rendering');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Kodak Portra 400 grain, shallow DOF, Portra earth tone grading');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Kodak Portra 400 grain, shallow DOF, Portra earth tone grading');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Kodak Portra 400 grain, shallow DOF, Portra earth tone grading');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Kodak Portra 400 grain, shallow DOF, Portra earth tone grading');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Kodak Portra 400 grain, shallow DOF, Portra earth tone grading');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'Kodak Portra 400 grain, shallow DOF, Portra earth tone grading');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'iPhone camera quality, natural grain, 9:16 vertical aspect ratio');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'iPhone camera quality, natural grain, 9:16 vertical aspect ratio');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'iPhone camera quality, natural grain, 9:16 vertical aspect ratio');
INSERT INTO harvested_tokens (token, value) VALUES ('Technical', 'iPhone camera quality, natural grain, 9:16 vertical aspect ratio');
